### PR TITLE
Insecure dependency in kill in _is_tainted() while running under -T

### PR DESCRIPTION
**Pull request by ddoyle**
Clone of PR #30, just making sure this passes.  There is a taint test that covers this.

### CODE REVIEW

**Comment by oalders** [comment]
Looks good to me!

**Comment by petdance** [comment]
I would just replace all the uses of `_is_tainted` with a call to the proper `tainted` func.

And if we keep the `_is_tainted` then get rid of the `no warnings`

**Comment by petdance** [comment]
If Travis is happy, I'm happy.

**Comment by ddoyle** [comment]
Travis is happy. hoorah

**Comment by oalders** [comment]
Thanks!

**Pull request merged**
