### PR TITLE
Bump minimum Perl to 5.8

### LINKED ISSUE #351: Raise minimum Perl to 5.8
ATM This dist claims to support Perl 5.6, however:

 - We don't test on 5.6, 5.8 is the lowest GitHub Actions goes.
 - Many of our dependencies only support 5.8+ like `HTML::Form`, `HTML::HeadParser`, `HTTP::Cookie`, etc. So in practice it's impossible to install a modern `WWW::Mechanize` on 5.6.
 - CPANTS doesn't even go back that far, so clearly no one is using 5.6 - http://matrix.cpantesters.org/?dist=WWW-Mechanize+2.14

Additionally we can do some slight code cleanup as our test suite currently does this in a bunch of files:
```perl
delete @ENV{qw( PATH IFS CDPATH ENV BASH_ENV )};  # Placates taint-unsafe Cwd.pm in 5.6.1
```

### PR DESCRIPTION
**Pull request by JRaspass**
Fixes #351

### CODE REVIEW

**Review by simbabque — APPROVED** [review]
LGTM. Thank you!

**Comment by simbabque** [comment]
This looks like a sound change that we should do. @oalders what do you think?

**Comment by oalders** [comment]
That sounds good to me. @petdance?

**Comment by oalders** [comment]
Thanks @JRaspass. There was a merge conflict, so I merged this at the command line via 2f7a0f4dd16bbd34

**Pull request closed without merging**
