### PR TITLE
mech-dump errors when a request failed #292

### LINKED ISSUE #292: mech-dump should say when local file not found
```
$ mech-dump file:///$RANDOM
file:///13706 returns type "", not "text/html"
```
It should just say Error: file not found.

### PR DESCRIPTION
**Pull request by simbabque**
Fixes #292

### CODE REVIEW

**Review by oalders — APPROVED** [review]
Great! This just needs a merge conflict resolved.

**Comment by simbabque** [comment]
Done, thanks.

**Comment by oalders** [comment]
Any idea what's up with the Windows failures?

**Comment by simbabque** [comment]
> Any idea what's up with the Windows failures?

Not exactly. I found https://stackoverflow.com/a/32054866/1331451, which points to something with `system` setting `$?` to `-1` on Windows in 5.14 (and possibly 5.16?) being broken. If that is the case, it must have been fixed later, but I could not find any fixes in perldelta. I have now skipped this one test case on these versions.

Please have another look. Thanks.

**Review by oalders — APPROVED** [review]
\o/

**Pull request merged**
