### PR TITLE
Prefer q{} over ''

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by haarg** [comment]
Do we have a perlcritic rule for this?

**Comment by oalders** [comment]
We haven't been able to introduce `perlcritic` yet. Now that the PRs have been cleared out, we can start to ramp up on code quality etc.

**Comment by oalders** [comment]
This is just using my own fork of https://metacpan.org/pod/App::PerlNitpick. I'm just messing around with it to see where it breaks and it seemed fine on this repo.

**Review by simbabque — APPROVED** [review]
LGTM. I strongly agree with these changes, and I hope we can bring that in as a critic rule once we're there.

**Pull request merged**
