### PR TITLE
add test for dump_forms with multiple multiselelects

### LINKED ISSUE #133: WM: Select multiple field not being shown in Mechanize
prasad...@gmail.com reported on Dec 13, 2007 

<pre>
<b>What steps will reproduce the problem?</b>
1. I have a HTML page which has 6 selects and last 2 are select mutiples.
The last select mutiple is not being shown into the Mechanize form dump.
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>

I am working on Linux and using WWW-Mechanize 1.34.

<b>Please provide any additional information below.</b>

 
</pre>

### Details

Imported from [Google Code issue 41](http://code.google.com/p/www-mechanize/issues/detail?id=41) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=41)

* **Type**:      Defect
* **Date**:      Dec 13, 2007
* **Reporter**:  prasad...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Mar 12, 2008 :

<pre>
(No comment was entered for this change.)
</pre>

* Summary : WM: Select multiple field not being shown in Mechanize

**jordan.m...@gmail.com** commented on Jul 10, 2008 :

<pre>
Works for me.  Attached is the document I used to test.
</pre>

**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

### PR DESCRIPTION
**Pull request by simbabque**
Closes #133

### CODE REVIEW

**Comment by simbabque** [comment]
@oalders, same thing as in my previous PR. The macos build failed because it couldn't install a dependency. I've not restarted the job this time.

**Comment by oalders** [comment]
If it's just 5.8 on macOS then I think we can disable it that build. Not sure how important that one is.

**Comment by simbabque** [comment]
> If it's just 5.8 on macOS then I think we can disable it that build. Not sure how important that one is.

I reran them now. All green. Seems very hicuppy to me.

**Review by oalders — APPROVED** [review]

**Comment by oalders** [comment]
Yeah, that flaky build is unfortunate. :( Thanks for the test!

**Pull request merged**
