### PR TITLE
extract image links also from css

### PR DESCRIPTION
**Pull request by jozef**
Hi,

here is patch that allows WWW::Mechanize to recognize and extract links from <style> && style="" && .css.

Cheers
Jozef

### CODE REVIEW

**Comment by oalders** [comment]
Closing and re-opening to trigger a Travis build.

**Comment by simbabque** [comment]
> Closing and re-opening to trigger a Travis build.

I'm doing the same again.

**Comment by oalders** [comment]
I think this will need to forked and rebased at the very least..

**Comment by simbabque** [comment]
> I think this will need to forked and rebased at the very least..

I'm on that.

**Comment by simbabque** [comment]
I've got it rebased and fixed, so the tests are all passing in my copy.

The implementation suggested by @jozef makes all WWW::Mechanize::Image objects created via this new code have the `tag` attribute set to `css`, and does not set any other attributes like `name` or `alt`, or the catch-all `attr`. 

This makes it easy to distinguish which ones came from style, but it's harder to find the ones you want. Since `css` isn't a tag, I am unsure if that's a clean way of doing this. Maybe it could work as follows:

- for `<style>...</style>`, set the `tag` to `style`, and collect all the attributes
- for `<foo style="..." />`, set the tag to `foo` and collect all the attributes, including `style="..."`.
- for CSS files, which we can also parse with the new code, set `tag` to `undef` as there's no tag

The only problem with this approach is that there's no way to clearly see that an image came from an inline `style` attribute. If we consider this edge case, which already parses correctly, this might be clearer.

```html
<img src="https://via.placeholder.com/150" 
     style="background-image: url(https://via.placeholder.com/50.png/ff0000); padding: 100px">
```
example image


There are two images in this. Parsing this tag will return both images, with the one from `src` coming first. But with my approach above, both of them would look like they are from the `` tag and there would be no way to tell which one was the background that was set in the `style` attribute.

We could of course say that this is such a marginal edge case we just ignore it. I'm fine with that.

I also need to add documentation.

**Comment by oalders** [comment]
@simbabque your approach sounds good to me.  Do you have a PR for this?

**Pull request closed without merging**
