### PR TITLE
Document that click_button dies if no button is found

### LINKED ISSUE #136: WM: click_button does not check for zero matching inputs
wdha...@gmail.com reported on Mar 26, 2008 

<pre>
<b>What steps will reproduce the problem?</b>
1. Create a form with a tag like &lt;button type=&quot;submit&quot; name=&quot;foo&quot; value=&quot;bar&quot;&gt;
2. call -&gt;click_button( name =&gt; &quot;foo&quot; )

<b>What is the expected output? What do you see instead?</b>
HTML::Form doesn&#39;t support the &lt;button&gt; tag, so the call to
$form-&gt;find_input in click_button() doesn&#39;t return anything and $request
never gets assigned to. The call to $self-&gt;request a few lines later then
causes an error like this:

Can&#39;t call method &quot;header&quot; on an undefined value at
/usr/local/lib/perl5/5.8.8/WWW/Mechanize.pm line 2227.

Ideally click_button should give an error/warning if no matching inputs are
found.

<b>What version of the product are you using? On what operating system?</b>
1.34 on FreeBSD 6.4

<b>Please provide any additional information below.</b>
</pre>

### Details

Imported from [Google Code issue 45](http://code.google.com/p/www-mechanize/issues/detail?id=45) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=45)

* **Type**:      Defect
* **Date**:      Mar 26, 2008
* **Reporter**:  wdha...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Nov 21, 2008 :

<pre>
(No comment was entered for this change.)
</pre>

* Summary : WM: click_button does not check for zero matching inputs

**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

### PR DESCRIPTION
**Pull request by simbabque**
Also add regression tests for #136 to prove that <button> tags indeed
work with our HTML::Form version now.

Closes #136.

### CODE REVIEW

**Comment by simbabque** [comment]
This is curious. The coverage build had a port already in use, and the macos one couldn't install a dependency. Weird.

**Review by oalders — APPROVED** [review]
Great! Thanks @simbabque.

**Comment by oalders** [comment]
> This is curious. The coverage build had a port already in use, and the macos one couldn't install a dependency. Weird.

I don't see that in the logs. Do you have a link handy?

**Comment by simbabque** [comment]
> > This is curious. The coverage build had a port already in use, and the macos one couldn't install a dependency. Weird.
> 
> I don't see that in the logs. Do you have a link handy?

I rerun the job. The direct links in my email notification seem to still work:

- Coverage failed (1 annotation): https://github.com/libwww-perl/WWW-Mechanize/runs/1200301105
- 5.30 on macos-latest failed (1 annotation): https://github.com/libwww-perl/WWW-Mechanize/runs/1200312687
- and two follow-ups in macos cancelled because of the 5.30 fail

-

**Pull request merged**
