### PR TITLE
Fix kwalitee issues

### PR DESCRIPTION
**Pull request by kyzn**
Hi! Thanks for maintaining `WWW-Mechanize`. It was our assignment for April's CPAN Pull Request Challenge, and we are about to send a couple pull requests :)

Please do let me know if you want anything updated. Thanks!

build_prereq_matches_use: Add modules in test suite to dist.ini
meta_yml_has_provides: Add [MetaProvides::Package]
meta_yml_declares_perl_version: Add perl 5.8.9 as minimum
  [MinimumPerl] gave 5.13.10, which was high. I went with the min
  version with all-passes for WWW-Mechanize 1.8.4 at CPANTesters Matrix

\#cpan-prc \#team-ziprecruiter

### CODE REVIEW

**Comment by karenetheridge** [comment]
We do not want things like Test::Pod::* in test prerequisites. These are for author testing only.

We shouldn't be raising the minimum perl version unnecessarily. If we simply want *something* to go in there, it should be 5.006.

**Comment by karenetheridge** [comment]
@kyzn what file/syntax told you that perl 5.13.10 was required? I only see syntax requiring 5.8 (two-arg open, two-arg binmode).

**Comment by kyzn** [comment]
@karenetheridge: 
Re: ExtraTest, thanks for description! That makes sense. I can update that easily.
Re: MinimumPerl...
When I run `dzil build` with `[MinimumPerl]`, META.json gets
- perl 5.008 in configure.requires
- perl 5.013010 in runtime.requires
- perl 5.013010 in test.requires

However, when I do `perlver`, I get the same two places (bin/mech-dump `binmode` and t/dump.t `open`) for 5.8 and nothing higher.

So I did some debugging around, and these were the files making [MinimumPerl] think that it requires 5.13.10...

```
test -- 5.013010 -- t/area_link.html
test -- 5.013010 -- t/field.html
test -- 5.013010 -- t/find_frame.html
test -- 5.010    -- t/find_inputs.html
test -- 5.013010 -- t/find_link.html
test -- 5.013010 -- t/find_link_id.html
test -- 5.010    -- t/form_with_fields.html
test -- 5.013010 -- t/frames.html
test -- 5.013010 -- t/google.html
test -- 5.013010 -- t/image-parse.html
test -- 5.013010 -- t/local/nonascii.html
test -- 5.013010 -- t/save_content.html
test -- 5.013010 -- t/select.html
test -- 5.013010 -- t/tick.html
test -- 5.013010 -- t/upload.html
```
Indeed, when I removed html files.. It went back to 5.008. 
Another issue with [MinimumPerl] is that it's actually using Perl::MinimumVersion 1.26, whereas Neil's latest version is 1.38.. I guess I just found a couple new PR ideas.

So.. Would it make sense to keep the minimum as 5.8 for those two places, or would you prefer it to be appear as 5.6?

**Comment by karenetheridge** [comment]
> Another issue with [MinimumPerl] is that it's actually using Perl::MinimumVersion 1.26, whereas Neil's latest version is 1.38..

Not quite -- it's using whatever the user has installed on their system, where 1.26 is just the *minimum* version.  Unless there's something broken in 1.26, the minimum version doesn't need to be raised.

perl 5.8 is only required for tests, not runtime code, so the versions could either be set separately for each phase, or should just be left at 5.6 throughout.

**Comment by kyzn** [comment]
> Not quite -- it's using whatever the user has installed on their system, where 1.26 is just the minimum version. Unless there's something broken in 1.26, the minimum version doesn't need to be raised.

Ah, of course. You're right. Thanks!

> perl 5.8 is only required for tests, not runtime code, so the versions could either be set separately for each phase, or should just be left at 5.6 throughout.

Turns out, you cannot really specify two different versions for two different phases. Dist::Zilla has a feature to synchronize versions across runtime, build and test phases. I think I can submit a patch to change that, but I highly doubt it will be merged.

So, I guess I'll just put 5.006 into dist.ini. What we have right now already lets you install with 5.6 anyway, so let's at least prevent from going even lower than that?

**Comment by karenetheridge** [comment]
> Dist::Zilla has a feature to synchronize versions across runtime, build and test phases. I think I can submit a patch to change that, but I highly doubt it will be merged.

It's not really a feature so much as a workaround for some issues in older versions of the CPAN.pm client that don't handle different prereq phases very well -- so you're right, it would 't be merged.

**Comment by oalders** [comment]
@karenetheridge are we ok to merge this?

**Comment by oalders** [comment]
Thanks @kyzn!

**Pull request merged**
