### PR TITLE
Issue 214: add ability to clear history and tests for history

### LINKED ISSUE #214: Please add clear_history method
fumeoftheday reported on Jul 5, 2012 

<pre>
<b>What steps will reproduce the problem?</b>
1. N/A
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
N/A

<b>What version of the product are you using? On what operating system?</b>
All.

<b>Please provide any additional information below.</b>

Sometimes when a website misbehaves I find that I want to be able to reset things because the back() method won&#39;t do what I want.  I&#39;d like to be able to clear the history so that back() fails and I can reload the data using get.

I could delete the object and create a new one - but I&#39;d rather not.

</pre>

### Details

Imported from [Google Code issue 237](http://code.google.com/p/www-mechanize/issues/detail?id=237) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=237)

* **Type**:      Defect
* **Date**:      Jul 5, 2012
* **Reporter**:  fumeoftheday
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

### PR DESCRIPTION
**Pull request by mschae94**
closes #214

### CODE REVIEW

**Comment by petdance** [comment]
Sounds good to me.  Are you wanting me to do something?

**Comment by oalders** [comment]
> Do we need to clear other variables such as $self->{req}, $self->{res} too?

I think since this is just deleting the stack, we want to keep the information for the last request around. https://metacpan.org/source/OALDERS/WWW-Mechanize-1.88/lib/WWW/Mechanize.pm#L206-218

**Comment by oalders** [comment]
@petdance if you had a moment to eyeball the code, that would be helpful.  I didn't see any issues, but more eyes on the code is better.

**Comment by petdance** [comment]
I think `$self->{page_stack}` should get reinitialized to an empty `[]`, just like in `new`, after it gets `delete`d.

Are we still supporting Perls all the way back to 5.6.1?  Even on ack I require 5.10.1.

The test seems to be mixing Test and Test2 style matches.  I'm seeing both `isa` and `isa_ok`.

That's all I'm seeing.  All seems sensible to me.

**Comment by skaji** [comment]
@oalders 
> I think since this is just deleting the stack, we want to keep the information for the last request around. 

I see.

**Comment by oalders** [comment]
>Are we still supporting Perls all the way back to 5.6.1? Even on ack I require 5.10.1.

We've been keeping stuff backwards compatible as far as possible unless there's a compelling reason not to.

> I'm seeing both isa and isa_ok.

Yeah, I'm not sure `isa_ok()` is providing much benefit. We could probably delete those checks.

> That's all I'm seeing. All seems sensible to me.

Thanks for the review @petdance!

**Comment by mschae94** [comment]
> The test seems to be mixing Test and Test2 style matches. I'm seeing both isa and isa_ok.

Actually, for the `isa_ok`, I have copied some codes from the existing tests for the consistency purpose.
For the `isa`, this is one of the special comparisons provided by [Test::Deep](https://metacpan.org/pod/Test::Deep#isa).

> I think $self->{page_stack} should get reinitialized to an empty [], just like in new, after it gets deleted.

In [`_push_page_stack`](https://github.com/libwww-perl/WWW-Mechanize/blob/master/lib/WWW/Mechanize.pm#L3101) it reinitializes to an empty `[]` if `$self->{page_stack}` does not exist. Therefore, we can simply delete the key i guess.

**Comment by simbabque** [comment]
For what it's worth, I don't see any issues with the changes either. But I'm just a passer-by and I've helped @mschae94 implement them. :)

**Comment by oalders** [comment]
Thanks @mschae94, @petdance, @skaji and @simbabque!

**Pull request merged**
