### PR TITLE
tick() now dies if checkbox is not found

### LINKED ISSUE #239: tick() doesn't die on error
`tick` warns on error instead of dying, which doesn't match the documentation.

https://metacpan.org/pod/WWW::Mechanize#$mech-%3Etick(-$name,-$value-%5B,-$set%5D-):

> Dies if there is no named check box for that value.

https://metacpan.org/source/OALDERS/WWW-Mechanize-1.86/lib/WWW/Mechanize.pm#L885-886:

```perl
    # got self far?  Didn't find anything
    $self->warn( qq{No checkbox "$name" for value "$value" in form} );
```

That means code like:
```perl
eval { $mech->tick($field, $value); }
if ($@) {
    ...
}
```
doesn't actually detect errors (`tick` never dies) and spews warnings (because `eval` only catches exceptions, not warnings).

### PR DESCRIPTION
**Pull request by oalders**
This behaviour is now in line with the documentation.

Fixes #239

### CODE REVIEW

**Comment by petdance** [comment]
Looks fine to me.  That "got self far" instead of "got this far" is kind of amusing. :-)

**Comment by oalders** [comment]
Thanks @petdance! I did check the commit that introduced "got self far" and I confirmed that it was only a typo and not some comment that I just didn't understand.  :)

**Comment by petdance** [comment]
It seemed to me that maybe someone was making a global search and replace from "this" to "self", like they were coming from PHP or something because PHP's standard is `this` for the object you're in.

**Comment by oalders** [comment]
Ah, you're right, that's the find and replace that triggered it, but I'm not sure if it was someone coming from PHP.  ;)  https://github.com/libwww-perl/WWW-Mechanize/commit/e25b0582

**Comment by petdance** [comment]
Ha!  Back in 2003, I was indeed doing a lot of PHP. :-)

**Pull request merged**
